# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookwriter', models.CharField(max_length=100)),
                ('bookyear', models.DateField(default=datetime.date.today)),
                ('bookpress', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('bookcover', models.CharField(max_length=150)),
                ('usernumber', models.IntegerField()),
                ('onepoint', models.IntegerField()),
                ('twopoint', models.IntegerField()),
                ('threepoint', models.IntegerField()),
                ('fourpoint', models.IntegerField()),
                ('fivepoint', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('photo', models.ImageField(upload_to='upload')),
                ('region', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Book_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('bookid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('point', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
            ],
        ),
    ]
