# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('bookname', models.CharField(max_length=100)),
                ('bookwriter', models.CharField(max_length=100)),
                ('bookyear', models.DateField()),
                ('bookpress', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=100)),
                ('bookcover', models.CharField(max_length=100)),
                ('usernumber', models.IntegerField()),
                ('onepoint', models.IntegerField()),
                ('twopoint', models.IntegerField()),
                ('threepoint', models.IntegerField()),
                ('fourpoint', models.IntegerField()),
                ('fivepoint', models.IntegerField()),
                ('point', models.IntegerField()),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
