# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-20 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellbook', '0002_auto_20160720_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='bookyear',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
