# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-07-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shellbook', '0004_remove_book_info_bookid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('photo', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
